sky:
  minio:
    endpoint: http://47.92.138.20:9000/
    access-key: zhouhan
    secret-key: ZHOUhan@123
    bucket-name: porridgehank-test1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.92.138.20
    port: 3306
    database: sky_take_out
    username: root
    password: zhouhan123
  redis:
    host: 47.92.138.20
    port: 6379
#    password: 123456
    database: 10
  wechat:
    appid: wxdf392e07cf727b11
    secret: c9e614721e8333268bfe6b7642da7a74

